analyzer:
  errors:
    invalid_annotation_target: ignore

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    depend_on_referenced_packages: false
    prefer_const_constructors: false
    prefer_const_constructors_in_immutables: false
    prefer_const_literals_to_create_immutables: false
